### ISSUE TITLE
offlineInstaller doesnt work with taiHEN

### ISSUE THREAD

**Issue by stranno** [yifanlu/taiHEN#17]
It seems it is not detecting the mail database correctly, it keep asking to enter and close the application in order to create the database.

![2016-11-08-224932](https://cloud.githubusercontent.com/assets/6293197/20118612/71d844ce-a605-11e6-9a51-cc6e7c8d7978.jpg)

HENkaku works fine.

**Comment by yifanlu** [comment]
Not an issue. The beta is not for offline installer.
