### ISSUE TITLE
Cannot create ux0:tai/config.txt

### ISSUE THREAD

**Issue by tippisum** [yifanlu/taiHEN#19]
Cannot create ux0:tai/config.txt.
Failed with Error 0x80010011 when trying to create it using shell.
The file cannot be created by copying, renaming or FTP.
Any other file under ux0:tai can be accessed normally, except for config.txt.

Using the latest taiHEN and have unsafe homebrew enabled.

**Comment by yifanlu** [comment]
Use vitashell.
