### ISSUE TITLE
Kernel module unloading does not work.

### ISSUE THREAD

**Issue by Stary2001** [yifanlu/taiHEN#20]
load:
```
modid = taiLoadStartKernelModule("ux0:app/STAR00001/test.skprx", 1, arg, 0);
```
returns successfully (with a module uid).
unload:
```
int res = taiStopUnloadKernelModule(modid, 1, arg, 0, NULL, &kmod_res);
```
returns 0x8002d002 (SCE_KERNEL_ERROR_MODULEMGR_IN_USE)
and if trying to load again, load returns 0x8002d013 (SCE_KERNEL_ERROR_MODULEMGR_OLD_LIB)

**Comment by yifanlu** [comment]
e1b04bc1c89f3ebf77a9f51a8c4bb5cb718e4180 should fix part of the problem (releasing the uid too early). Can you try `taiUnloadKernelModule` and see if that works?

**Comment by Stary2001** [comment]
nope - when i use 

```
int res = taiUnloadKernelModule(modid, 0);
```

instead, i get what appears to be a kernel panic(?) - instant reboot, "a problem has occurred.." popup on next boot.
that did fix the uid problem, though.

**Comment by yifanlu** [comment]
Regarding 0x8002d002, this is because your kernel module exports to user. This is a kernel non-feature (there seems to be no cleanup in this case).

**Comment by yifanlu** [comment]
If you want to override this, add a hook to `SceSblACMgrForKernel` for function NID `0xBBA13D9C` imported by `SceKernelModulemgr`. The prototype is `int SceSblACMgrForKernel_BBA13D9C()` and make it return 1 if you want to bypass the kernel's prohibition of stopping a syscall exporting module.
