### ISSUE TITLE
a plugin to make vita screen more dimmer (feature request).

### ISSUE THREAD

**Issue by Fadi5555** [yifanlu/taiHEN#22]
@yifanlu hi there. Well first of all I wank to congratulate you about this amazing job.
Well after we finally getting vita CFW I'm really hope to get a plugin to make vita screen dimmer than this. Because vita screen is to bright even with lowest one. So I'm really hope we can get a plugin for that. At least if you could port (bright v0.3 plugin) that on psp. Or even if you could get like cydia tweak which is called (f.lux) this tweak make the screen more yellow to keep our eyes comfort specially when we playing for long time in a dark room.
This is my request and I'm sure many of people really want this plugin as well.
Thanks.

**Comment by yifanlu** [comment]
Hi, this is not the right place for non framework related stuff. Consider posting to the /r/vitahacks subreddit or something.
