### ISSUE TITLE
Request: Expose FindExport/FindImport

### ISSUE THREAD

**Issue by TheOfficialFloW** [yifanlu/taiHEN#29]
This will be useful for quickly test/use functions

**Comment by DaveeFTW** [comment]
Should we have a "debug" or "developer" version of taiHEN with these useful exports? Mostly to discourage lazy techniques for release. That is of course, you can think of a legitimate reason to have FindExport/FindImport in a release plugin?

**Comment by yifanlu** [comment]
I think I'll export the calls but not include any headers. Devs would have to manually get the headers from taihen--at which they can easily add the export themselves if they really need it.
