### ISSUE TITLE
Retroarch and mgba not working with taiHENkaku

### ISSUE THREAD

**Issue by yifanlu** [yifanlu/taiHEN#31]

**Comment by yifanlu** [comment]
Problem is in missing a patch in HENkaku. That patch was skipped because libsubstitute didn't support it.

**Comment by parkerlreed** [comment]
FWIW RetroArch is working fine in taiHen for me. Using the November 17th build.

**Comment by yifanlu** [comment]
Yes because you are using henkaku. That was a workaround due to a problem in taihen (as noted here).

**Comment by yifanlu** [comment]
Fixed in latest HENkaku.
