### ISSUE TITLE
Allow patching/injection of functions that libsubstitute can't handle

### ISSUE THREAD

**Issue by yifanlu** [yifanlu/taiHEN#32]
If a function includes a conditional branch in the first 8 bytes, libsubstitute can't hook it. We need an alternative way of patching these functions or stuff like the patch for `0xD514BB56` won't work.

**Comment by TheOfficialFloW** [comment]
I'd suggest hijacking the export/import func tables. This method would not heavily modify code.

**Comment by yifanlu** [comment]
Unfortunally that won't work in this case.
