### ISSUE TITLE
Error in taiLoadKernelModule ?

### ISSUE THREAD

**Issue by Cpasjuste** [yifanlu/taiHEN#4]
I wonder if there is an error in the taiLoadKernelModule function. The header says to set "opt" to NULL if i understand correctly, but "opt" is checked for not NULL : https://github.com/yifanlu/taiHEN/blob/master/taihen-user.c#L356

**Comment by yifanlu** [comment]
You're right. Will fix this when I get the chance. Those functions have not been tested/looked at. Priority is getting everything else stable first.

**Comment by yifanlu** [comment]
Fixed in latest commit.
