### ISSUE TITLE
Question about permissions in taihenkaku and plugins

### ISSUE THREAD

**Issue by Rezasdemon** [yifanlu/taiHEN#40]
is there a detailed explaination on how the permissions works and how to use in source?

like do i need to define _Kernel_ somewhere to elevate my app during compile to build using the unsafe homebrew flag ? am i completely wrong ? how does it work ? i understand there is a flag on eboot.bin's for their unsafe homebrew etc , does a plugin only gain the access of the app its running in ? if i use taihen config.txt and write 
*main 
ux0:plugins/rezapeek.suprx  # can i do this ? does a suprx and s skprx make a difference other then name ?

and will this only have access to the memory allocated by pcse ? 
i guess my question is the memcpy user to kernel and kernal to user and also  C memcpy does that work with what level of permisions ? does it error on certain calls to protected memory which with other access would be readable?
*pcseXXXXX
ux0:plugins/rezapeek.suprx

**Comment by yifanlu** [comment]
You need to create a kernel module (skprx) to run it in kernel. Join us in freenode irc [#vitadev](irc://irc.freenode.net) and we can explain in more detail.
