### ISSUE TITLE
Crash when changing wifi hotspot using "Wi-Fi Settings"

### ISSUE THREAD

**Issue by philippecr** [yifanlu/taiHEN#42]
The steps are,
1) I installed taiHEN, restarted the Vita
2) Turn it on, initiate taiHEN.
3) Launch "Setting"
4) Press on "Wi-Fi Settings", and it crashed.

Can't recreate the problem now.

**Comment by yifanlu** [comment]
Did the settings app crash or the entire vita?

**Comment by philippecr** [comment]
The entire Vita.  

Need to long press power button to restart

**Comment by yifanlu** [comment]
I wonder if this is similar to something I've experienced without henkaku. Sometimes wifi settings freeze but it's not a crash if you wait like half a minute it resumes.

**Comment by yifanlu** [comment]
I believe this is resolved with https://github.com/henkaku/henkaku/issues/32
