### ISSUE TITLE
Partition Question

### ISSUE THREAD

**Issue by ShadyDemoness** [yifanlu/taiHEN#43]
Hy Team Henkaku

Could you please add a switch to the taihen settings in order to see and write to the other partitions.
Also I can't write to the root of ux0 like creating folders and so on and a few folders are even hidden in ux0 like the game folder.

I don't persist on the switch, but please fix the ux0 partition.

Regards DarkLPs

**Comment by yifanlu** [comment]
Thanks for the suggestion but such a feature would work better as a third party plugin.

If you want full access to ux0 use vitashell

**Comment by ShadyDemoness** [comment]
the thing is it even doesn't work with vitashell

**Comment by yifanlu** [comment]
Do you have unsafe home brew enabled? Then restarted and opened vitashell?

**Comment by ShadyDemoness** [comment]
Hy,

Sorry I bothered you with such a stupid issue which isn't Even one, because I'm to stupid to read Readmes.

Really sorry.
Thanks for helping me though.
Works now.
