### ISSUE TITLE
Potential issue with plugin loading in PSP emu

### ISSUE THREAD

**Issue by yifanlu** [yifanlu/taiHEN#47]
Someone in chat built a suprx that crashes when loaded after adrenaline but loads fine with settings.

**Comment by ghost** [comment]
i have tried my plugin without adrenaline, and that doesn't work
but show an error now: C1-2858-3

settings app work fine, with printf and sceIoMkdir

EDIT: Went pspemu was launched, the plugin succefully  create an folder in data, but crash the app

**Comment by yifanlu** [comment]
Closing due to lack of information.
