### ISSUE TITLE
failed installation; C0-15008-4 and browser is unaccessible

### ISSUE THREAD

**Issue by toir11** [yifanlu/taiHEN#48]
During taiHenkaku installation, Vita crashed almost immediately with the following error: [C2-14185-9:](http://static.diary.ru/userdir/3/3/9/3/3393835/84623088.jpg) 
'A problem occurred the last time the PS Vita system was used, and the system did not power off correctly'. 

Error History also shows this, though I did not see this error appear: [C1-6775-5](http://static.diary.ru/userdir/3/3/9/3/3393835/84623091.jpg)
 'An error occured'.

Now, opening the browser in any case gives this error: [C0-15008-4](http://static.diary.ru/userdir/3/3/9/3/3393835/84623092.jpg)
'A serious error has occured in the system software. This system will restart'. 
Vita restarts in the safe mode with only two options: restart this system and restore this system. 
Error History shows another error that occurs at the same time but isn't shown: [C0-11478-1](http://static.diary.ru/userdir/3/3/9/3/3393835/84623095.jpg)

Regular Henkaku is still accessible through the offline installer. Rebuilding the database didn't work and I don't want to risk formatting my system and be left without both browser and offline installer in case restoring doesn't fix the error.
There is no tai folder in ux0, so I assume it didn't install at all.

**Comment by yifanlu** [comment]
I think the last HENkaku release should have fixed this.
