### ISSUE TITLE
Might be a bug with file system reading 

### ISSUE THREAD

**Issue by cysin** [yifanlu/taiHEN#51]
I am using retroarch pcsx rearmed and it behaves differently between 'henkaku' and 'taihen'. With henkaku (go.henkaku.xyz), it loads game image files fine; but with 'taihen'(beta.henkaku.xyz) it is very unstable, retroarch always reports 'no items' when open a game image file. So i am 99% sure it might be a bug with 'taihen'.

**Comment by yifanlu** [comment]
Hmm, I think this might just be chance as I don't make any fs related patches.

**Comment by yifanlu** [comment]
I believe the issue is caused by https://github.com/henkaku/henkaku/issues/32
