### ISSUE TITLE
taiHEN user plugin - sceCtrlPeekBufferPositive lead to Vita reboot

### ISSUE THREAD

**Issue by Scorpeg** [yifanlu/taiHEN#58]
Code is this one: http://pastebin.com/jVJVFMtW

When I attach it to any app - it leads to immediate reboot, probably kernel crash.

This is the modification of user.c in henkaku user plugin, no other modifications were made: https://github.com/henkaku/henkaku/tree/master/plugin

So basically to reproduce you can just replace user.c with mine.

**Comment by yifanlu** [comment]
It might be this https://github.com/yifanlu/taiHEN/issues/12

Test the workaround and let me know.

**Comment by Scorpeg** [comment]
Did this way: http://pastebin.com/esD5p8GX 
Still reboots.
