### ISSUE TITLE
Livetweet Bug

### ISSUE THREAD

**Issue by ghost** [yifanlu/taiHEN#59]
While TaiHenkaku Beta 8 (the December 15th build) is installed, LiveTweet for PS Vita will not work. Reboot to use it.

**Comment by yifanlu** [comment]
Please provide more information: what is the error? Can you provide any screenshots?

**Comment by ghost** [comment]
Yes. 

This is the app as it is upon loading - http://i.imgur.com/RLaGQw6.jpg

If you try tapping any of them then either nothing happens or this happens - http://i.imgur.com/vcMQsEF.jpg

Thanks for doing an awesome job btw! 😄

**Comment by yifanlu** [comment]
Just pushed an update. Can you test it? Reboot your vita and install again from beta.henkaku.xyz

**Comment by ghost** [comment]
It works! Thanks so much Yifan! You're a champion!
