### ISSUE TITLE
Problems in plugin "newlib"

### ISSUE THREAD

**Issue by DavisDev** [yifanlu/taiHEN#61]
Hello!
I am trying to create an mp3 audio player to plugin mode,
First create the code as any application, and it works,
Translate the code to be used as a plugin:
I use the flag -nostartfiles in the make,
And add a couple of functions in the main.c to evade the errors and use the newlib:
Int _free_vita_newlib () {
Return 0;
}
Int _fini () {
Return 0;
}
And finally add the export.yml and its command in the make.
When debugging the plugin in action, I notice that it is not heard, but the report indicates that it is working well internally ...

I do not know if it is due to long memory applications (buffers for samples, and readings),
Or it may be due to some failure in the newlib, since not doing _init_vita_newlib and __libc_init_array there may be incursions in the generic functions no?

Additionally it probe to use the sample of audio provided by vitasdk, and portandolo to plugin, and to arrive at some function of sceAudio, it generates a crash.

Greetings and thank you any help!

**Comment by yifanlu** [comment]
Do not use newlib in plugins. It is not supported.

**Comment by yifanlu** [comment]
This should be better documented and addressed by the toolchain or something: https://github.com/yifanlu/taiHEN/issues/49
