### ISSUE TITLE
Modules with sceAppUtil or sceAppMgr imports does not work

### ISSUE THREAD

**Issue by hyln9** [yifanlu/taiHEN#67]
Loading a suprx which imports sceAppUtil or sceAppMgr functions will cause black screen.
Tried to link with weak stubs but it didn't help.

**Comment by CelesteBlue-dev** [comment]
how did you fix it ?

**Comment by hyln9** [comment]
@CelesteBlue-dev on the one hand, i believe it's not a problem of taihen; on the other hand, although i don't have time to figure it out now, suprx of adrenaline uses them without any problem: https://github.com/TheOfficialFloW/Adrenaline/blob/ae51147a40bf020d8197d349f28406fa6ffc1db9/user/main.c#L821
