### ISSUE TITLE
Linker error when building c8e6e6a

### ISSUE THREAD

**Issue by llakssz** [yifanlu/taiHEN#76]
0.9, 0.10 build fine with the latest vitasdk installed.
But with the latest source:
> [ 82%] Linking C executable taihen
> CMakeFiles/taihen.dir/plugin.c.obj: In function \`plugin_load_config':
> plugin.c:(.text+0x6c): undefined reference to \`ksceKernelTryLockMutex'
> CMakeFiles/taihen.dir/plugin.c.obj: In function \`plugin_free_config':
> plugin.c:(.text+0x1b2): undefined reference to \`ksceKernelTryLockMutex'
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/taihen.dir/build.make:460: taihen] Error 1
> make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/taihen.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2

`cat /usr/local/vitasdk/version_info.txt`
> Built at 2017-08-09 08:28:22
> newlib            1b87d020b9319e63725a4d839bf4fe3dace2a13f
> pthread-embedded  d028a893d849cc8ce3fe2c30a97562ad2970e6a9
> samples           e140147487c235d00d7ff0d868ad627f2fdfa2e4
> vita-headers      98c869cd4c0d39c221cdeacfa82ff9b9d090faef
> vita-toolchain    25d343b448d4d4f9883b6f38e44a4e0ac8355865

I'm not sure what the problem is, or if this is  expected since it's not a release yet.

But, just to put it out there at least that it's not building.

Thanks for all the work. 🎅

**Comment by yifanlu** [comment]
Yes it's not done yet, please use an earlier commit.
