### ISSUE TITLE
Improve reloading config.txt

### ISSUE THREAD

**Issue by alpakeno** [yifanlu/taiHEN#77]
Add the ability to stop and unload module then start it for *main and other sections.
For *gameid it works when updating the plugin and starting the game,
but in *main it doesn't reload the plugin, which need to reboot PS Vita to use the new updated plugin.

**Comment by yifanlu** [comment]
This can't be done for technical reasons. For other apps, quitting and reopening the app reloads the plugin but for shell you have to reboot to reload shell.
